#cloud-config
runcmd:
  - echo 'This instance was provisioned by Terraform.' >> /etc/motd
  - mkdir /home/opc/sample
  - curl --fail -H "Authorization: Bearer Oracle" -L0 http://169.254.169.254/opc/v2/instance/metadata/oke_init_script | base64 --decode >/var/run/oke-init.sh
  - bash /var/run/oke-init.sh
  #- oci compute instance update --launch-options '{"network-type":"VFIO"}' --force
  - wget https://docs.oracle.com/iaas/Content/Resources/Assets/secondary_vnic_all_configure.sh
  - chmod 777 secondary_vnic_all_configure.sh
  - sudo ./secondary_vnic_all_configure.sh -c
